name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones disabled for better analysis
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore workloads
      run: dotnet workload restore
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
      
    - name: Check code formatting
      run: dotnet format --verify-no-changes
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=glennf_LocalMarketplace
          -Dsonar.organization=glennf
          -Dsonar.sources=.
          -Dsonar.exclusions=**/obj/**,**/bin/**
          -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml